### ISSUE TITLE
Delete key-value

### ISSUE THREAD

**Issue by mcib3d** [GReD-Clermont/simple-omero-client#39]
Hi @ppouchin ,

I am trying to automatically add key values from image names and I noticed there is no method to delete key values, or eventually addAndReplace. Did I miss something ? Thanks.

Thomas

**Comment by ppouchin** [comment]
Hi @mcib3d ,

To delete key/value pairs from an object, I think you should retrieve the list of map annotations linked to the object through 
[`getMapAnnotations`](https://api.igred.fr/simple-omero-client/5.9.2/fr/igred/omero/repository/GenericRepositoryObjectWrapper.html#getMapAnnotations(fr.igred.omero.Client)), then you should be able to [`unlink`](https://api.igred.fr/simple-omero-client/5.9.2/fr/igred/omero/repository/GenericRepositoryObjectWrapper.html#unlink(fr.igred.omero.Client,A)) or [`delete`](https://api.igred.fr/simple-omero-client/5.9.2/fr/igred/omero/Client.html#delete(fr.igred.omero.GenericObjectWrapper)) them.
It you want to unlink them, but remove orphaned annotations, you can use [`countAnnotationLinks`](https://api.igred.fr/simple-omero-client/5.9.2/fr/igred/omero/annotations/GenericAnnotationWrapper.html#countAnnotationLinks(fr.igred.omero.Client)) to check if an annotation is referenced elsewhere.

Does that answer your question?

**Comment by mcib3d** [comment]
Hi @ppouchin ,

Yes that is perfect. Thanks again.

Thomas
