### ISSUE TITLE
Example of TableWrapper with ROI

### ISSUE THREAD

**Issue by lldelisle** [GReD-Clermont/simple-omero-client#57]
Hi,
Sorry, I already have a question.
I would like to create a Table in omero with a column with ROIs.
I have a ResultTable (obtained with Analyze particle) and the corresponding ImageJ ROIs (in the overlay).
I tried to use `setProperty` on the ImageJ ROIs then add a column in my ResultTable.
But in omero there is no link between my table entries and my ROIs.
I am quite sure something is missing but I don't know what.
Would you mind to give an example?
Thank you.
My attempt was:
```groovy
// I built previously a Map<String, Roi> map_rois with the rois corresponding to the table where the key is "Slice" in the rt
// Building a list of ROIs to put in omero
List<Roi> rois =  new ArrayList<>(0)
for ( int row = 0;row<rt.size();row++) {
        int t = rt.getValue("Slice", row) as int
        // Get the corresponding ROI
        Roi temp_roi = map_rois.get(t)
        // Set name and property
        temp_roi.setName("Gastruloid_t" + t)
        temp_roi.setProperty("ROI", "Gastruloid_t" + t)
        rois.add(temp_roi)
        // Add a column with the same info
        rt.setValue("ROI", row, "Gastruloid_t" + t)
}
// Save ROIs to omero
image_wpr.saveROIs(user_client, ROIWrapper.fromImageJ(rois as List))	

// Create an omero table:
TableWrapper table_wpr = new TableWrapper(user_client, rt, image_wpr.getId(), rois as List, "ROI")

// upload the table on OMERO
table_wpr.setName(table_name)
image_wpr.addTable(user_client, table_wpr)

```

**Comment by ppouchin** [comment]
The ROIs need a "ROI_ID" property set with their ID on OMERO (which is done automatically when retrieving ROIs).
I think you need to add something like this after saving the ROIs:
```groovy
updatedRois = ROIWrapper.toImageJ(image_wpr.getROIs(user_client), "ROI")
TableWrapper table_wpr = new TableWrapper(user_client, rt, image_wpr.getId(), updatedRois, "ROI")
```

However, you'll retrieve all the ROIs, so if you have more than what you want, you may have to filter them. Or use Folders.

**Comment by ppouchin** [comment]
I'll try to improve the documentation...

**Comment by ppouchin** [comment]
Maybe I should modify the `fromImageJ` method so ImageJ Rois are updated with the OMERO ID.

**Comment by lldelisle** [comment]
Hi,
Thank you so much for your answer. It worked.
If I understand well this block: https://github.com/GReD-Clermont/simple-omero-client/blob/9442f4abe6d1e7e3bf5de2fac2c2be95ca625989/src/main/java/fr/igred/omero/annotations/TableWrapper.java#L408-L435
Only one of those 2 is sufficient:
- add the same label as in the result table as name: `temp_roi.setName("Gastruloid_t" + t)`
- add the same label as in the result table as property: `temp_roi.setProperty("ROI", "Gastruloid_t" + t)`

**Comment by ppouchin** [comment]
Well, it's also about what you want do display on OMERO:

- `setProperty("ROI", index)` is used to group 2D shapes into one 3D/4D ROI on OMERO. The value is never stored, and when you retrieve it from OMERO, the default values are integers.
- `setName(name)` is used to name the 2D shapes on OMERO (and in ImageJ).
- You can also use `setProperty("ROI_NAME", name)` to give a 3D/4D ROI a name on OMERO.

I try to match against any of those properties when ROIs are passed to a TableWrapper.

**Comment by lldelisle** [comment]
Thanks for the answer, I am not familiar with 3D/4D ROI on OMERO.
Just for info, when I tried to use `setProperty` with `index` of `int` type I got an error, it seems that it only accepts `String`...
