### ISSUE TITLE
Error in TableWrapper.addRows

### ISSUE THREAD

**Issue by lldelisle** [GReD-Clermont/simple-omero-client#70]
Hi,
I managed to throw an unexpected error which took me a lot of time to solve. 
Here are the versions I am using:
```
fiji-omero_ij             5.8.0                hdfd78af_0    bioconda
fiji-simple_omero_client  5.12.2               hdfd78af_0    bioconda
```
The error was:
```
java.lang.IllegalArgumentException: "Label" column not found                                                                        
        at ij.measure.ResultsTable.getValue(ResultsTable.java:472)                                                                  
        at fr.igred.omero.annotations.TableWrapper.addRows(TableWrapper.java:539)                                                   
        at fr.igred.omero.annotations.TableWrapper$addRows$0.call(Unknown Source)
        ....
```
I realized that the error was thrown by:
https://github.com/GReD-Clermont/simple-omero-client/blob/f301a73a3b418a359670f2877af737cec7c92406/src/main/java/fr/igred/omero/annotations/TableWrapper.java#L541
Because my tables had link to ROIs and these links were done by adding a column to the resultTable with the name "ROI".
While the class of the column Label was indeed String in the TableWrapper (created with the offset = 2).
I tried to add Rows from a table where `createROIColumn` did not worked. So offset was to 1 and then the class of the column in the TableWrapper of [offset + 0] was not String (as it is the ROI)...
However the check for size:
https://github.com/GReD-Clermont/simple-omero-client/blob/f301a73a3b418a359670f2877af737cec7c92406/src/main/java/fr/igred/omero/annotations/TableWrapper.java#L525-L527
Was not sufficient because `createROIColumn` delete the column with the ROI info if present.
So the number of columns between my TableWrapper and the ResultTable + offset (which was 1) was matching...
I think a way to avoid this would be either to store the offset value and check it matches or check that the first headings match the offset.

Lucille

PS: I am reporting bug but thank you so much for this tool

**Comment by lldelisle** [comment]
Thanks

**Comment by ppouchin** [comment]
PR #71 should "solve" this.
It should now throw the `IllegalArgumentException` saying `"Number or type of columns mismatch"`.

**Comment by lldelisle** [comment]
Thank you very much. This perfect.

**Comment by ppouchin** [comment]
[5.14.2 released](https://github.com/GReD-Clermont/simple-omero-client/releases/tag/5.14.2)
