### ISSUE TITLE
OMERO-Shapes default Channel

### ISSUE THREAD

**Issue by JensWendt** [GReD-Clermont/simple-omero-client#82]
Hello,

I used your `simple-omero-client` package in combination with the python package `pyimagej`.
I created ImageJ ROIs from Label images:
```
# get a ROI from an ImagePlus object by utilizing the wand tool on a x,y coordinate and "filling" it afterwards
def getRoi(imp, x, y, ip, cur_val):
    ij.IJ.doWand(imp, x, y, 0.0, "Legacy")
    roi = imp.getRoi()
    roi.setName(str(int(cur_val)))
    ip.fill(roi)
    return roi

# get a python lists of ImageJ ROIs from a file
def rois_from_label_image(imp):
    ip = imp.getProcessor()
    ip.setColor(0)
    roi_list = []
    for x in range(0,imp.getWidth(),2):
        for y in range(0,imp.getHeight(),2):
            cur_val = imp.getPixel(x,y)[0]
            if cur_val != 0:
                roi_list.append(getRoi(imp,x,y,ip,cur_val))
    imp.changes = False
    imp.close()
    return roi_list
```
These ROIs then converted and uploaded to OMERO:
```
# create a java array of RoiWrappers from the IJ ROI python list 
def transform_rois_to_java(roi_list):
    jRoiWrapper = jimport('fr.igred.omero.roi.ROIWrapper')
    roiwrapper = jRoiWrapper()
    rois_for_java = roiwrapper.fromImageJ(ij.py.to_java(roi_list))
    return rois_for_java

# function to save a java array of RoiWrappers to an OMERO Image, based on 'simple-omero-client'
def save_rois_to_image(client, rois_for_java, image_id):
    image_from_OMERO = client.getImage(jLng(image_id))
    image_from_OMERO.saveROIs(client, rois_for_java)
```

Doing it this way ends up with a default channel (i think 1) of the Shapes of the ROI.
This will lead to a bit of annoying behaviour in the OMERO.web iviewer.
You will only be able to see the ROIs when you have the channel they are "tied to" active/rendered.
If you change the channel of the Shape to `None` it will always be displayed (if you clicked "show") regardless of which channel you activated.
Do you have a specific reason for setting the default channel of the OMERO shape not to `None`, and if not so can you change this?
I searched through the code but could not find the correct line where it is set :/ otherwise I would have done a PR.

Best,

Jens

**Comment by ppouchin** [comment]
Hi!

If you set the channel position in ImageJ to 0, it should not be tied to a channel in OMERO I think:
https://imagej.net/ij/developer/api/ij/ij/gui/Roi.html#setPosition(int,int,int)

I keep the absolute position (channel, slice, frame) from ImageJ to OMERO, in case tying it to a channel is important.

**Comment by JensWendt** [comment]
I played around a bit, and you can only set it to an integer in ImageJ not `None`.
But then it seems the default would always be channel 0 as it will keep the 0 and transfer it to the OMERO channel 0.
I doubt that its a big deal for most applications/users, but for me it was annoying as I cobbled together a 16 channel image with ROIs.
Now always had to have the channel 0 showing for the ROIs to be visible, even if the channel 0 information was irrelevant for the visualization I wanted.

**Comment by ppouchin** [comment]
I'm sorry, I was in a rush. I said you should set the channel position to 0, but it depends on how it counts. 
If the first channel is 0, then you need to set it to -1. If the first channel is 1, then you set it to 0 (in macros for example).

In your case, it should probably be -1 actually.

**Comment by JensWendt** [comment]
Yes! -1 works. Thank you!!

**Comment by JensWendt** [comment]
Yes! -1 works. Thank you!!
